discuss/lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  # Algo similar a Interceptores/Filtros (logica antes de ejecutar el Request)
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # Cada que el usuario haga un Request, pasara por la logica de este Module Plug (Interceptor)
    plug Discuss.Plugs.SetUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

        #PREFIX
  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack

    #get "/", PageController, :index
    get "/", TopicController, :index
    get "/topics/new", TopicController, :new
    post "/topics", TopicController, :create
    get "/topics/:id/edit", TopicController, :edit
    put "/topics/:id", TopicController, :update
    delete "/topics/:id", TopicController, :delete
    get "/topics/:id", TopicController, :show

  end
        #PREFIX  (rutas para Ueberauth)
  scope "/auth", Discuss do
    pipe_through :browser # Use the default browser stack

    # tiene que ir al principio. ¿Porque?
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request # La funcion request es creada por Ueberauth en el controller
    get "/:provider/callback", AuthController, :callback     
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

discuss/lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Discuss · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!--
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    -->
    <%= csrf_meta_tag() %>

    <script>
      /* Generamos un Token para el usuario actual, y por el momento dentro de este Token solo
         estara guardado el user_id.
         La variable window.userToken, es la que se pasa a la funcion new Socket en el archivo socket.js, de
         esta forma estamos pasando al servidor el token y saber el user_id
      */
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>";
      <% end %>
    </script>

  </head>
  <body>
     <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>

        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: Routes.auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: Routes.auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>

      </div>
    </nav>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>